name: Call a reusable workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/canary.yaml
    with:
      goreleaser_file: 'goreleaser-canary.yml'
      snapshot: false