name: Call a reusable workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/canary.yaml
    with:
      goreleaser_options: '--snapshot'