name: Nightly
on:
  # schedule:
  #   - cron: '0 0 * * *' # Every day at midnight
  # pull_request:
  #   paths:
  #     - '.github/workflows/nightly.yaml'
  push:
    branches: [  ]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - uses: actions/checkout@v2

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.183.0
          args: release -f=goreleaser.yml --snapshot --skip-publish --rm-dist

      # Upload
      - name: Upload artifacts (FreeBSD-32bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*FreeBSD-32bit.tar.gz

      - name: Upload artifacts (FreeBSD-64bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*FreeBSD-64bit.tar.gz

      - name: Upload artifacts (FreeBSD-ARM.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*FreeBSD-ARM.tar.gz

      - name: Upload artifacts (FreeBSD-ARM64.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*FreeBSD-ARM64.tar.gz

      - name: Upload artifacts (Linux-32bit.deb)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-32bit.deb

      - name: Upload artifacts (Linux-32bit.rpm)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-32bit.rpm

      - name: Upload artifacts (Linux-32bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-32bit.tar.gz

      - name: Upload artifacts (Linux-64bit.deb)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-64bit.deb

      - name: Upload artifacts (Linux-64bit.rpm)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-64bit.rpm

      - name: Upload artifacts (Linux-64bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-64bit.tar.gz

      - name: Upload artifacts (Linux-ARM.deb)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-ARM.deb

      - name: Upload artifacts (Linux-ARM.rpm)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-ARM.rpm

      - name: Upload artifacts (Linux-ARM.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-ARM.tar.gz

      - name: Upload artifacts (Linux-ARM64.deb)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-ARM64.deb

      - name: Upload artifacts (Linux-ARM64.rpm)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-ARM64.rpm

      - name: Upload artifacts (Linux-ARM64.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-ARM64.tar.gz       

      - name: Upload artifacts (Linux-PPC64LE.deb)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-PPC64LE.deb

      - name: Upload artifacts (Linux-PPC64LE.rpm)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-PPC64LE.rpm

      - name: Upload artifacts (Linux-PPC64LE.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-PPC64LE.tar.gz     

      - name: Upload artifacts (Linux-s390x.deb)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-s390x.deb

      - name: Upload artifacts (Linux-s390x.rpm)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-s390x.rpm

      - name: Upload artifacts (Linux-s390x.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*Linux-s390x.tar.gz            

      - name: Upload artifacts (macOS-64bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*macOS-64bit.tar.gz  

      - name: Upload artifacts (macOS-ARM64.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*macOS-ARM64.tar.gz      

      - name: Upload artifacts (OpenBSD-32bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*OpenBSD-32bit.tar.gz  

      - name: Upload artifacts (OpenBSD-64bit.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*OpenBSD-64bit.tar.gz     

      - name: Upload artifacts (OpenBSD-ARM.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*OpenBSD-ARM.tar.gz 

      - name: Upload artifacts (OpenBSD-ARM64.tar.gz)
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/trivy_*OpenBSD-ARM64.tar.gz