name: Nightly-build
on:
  push:
    branches:
      - 'master'

env:
  GO_VERSION: "1.17"
  GH_USER: "aqua-bot"

jobs:
  Nightly-build:
    name: Nightly-build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Show available Docker Buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Setup Go 
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v1
        with:
          args: mod -licenses -json -output bom.json
          version: ^v1

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.183.0
          args: release --snapshot --skip-publish --rm-dist

      # Upload artifacts 
      - name: Upload artifacts (bom.json)
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            ./dist/trivy_*FreeBSD-32bit.tar.gz
            ./dist/trivy_*checksums.txt
      
      # - name: Upload artifacts (checksums.txt)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_checksums.txt
      #     path: ./dist/trivy_*checksums.txt
      #     if-no-files-found: error

      # - name: Upload artifacts (FreeBSD-32bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_FreeBSD-32bit.tar.gz
      #     path: ./dist/trivy_*FreeBSD-32bit.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (FreeBSD-64bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_FreeBSD-64bit.tar.gz
      #     path: ./dist/trivy_*FreeBSD-64bit.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (FreeBSD-ARM.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_FreeBSD-ARM.tar.gz
      #     path: ./dist/trivy_*FreeBSD-ARM.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (FreeBSD-ARM64.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_FreeBSD-ARM64.tar.gz
      #     path: ./dist/trivy_*FreeBSD-ARM64.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-32bit.deb)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-32bit.deb
      #     path: ./dist/trivy_*Linux-32bit.deb
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-32bit.rpm)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-32bit.rpm
      #     path: ./dist/trivy_*Linux-32bit.rpm
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-32bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-32bit.tar.gz
      #     path: ./dist/trivy_*Linux-32bit.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-64bit.deb)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-64bit.deb
      #     path: ./dist/trivy_*Linux-64bit.deb
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-64bit.rpm)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-64bit.rpm
      #     path: ./dist/trivy_*Linux-64bit.rpm
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-64bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-64bit.tar.gz
      #     path: ./dist/trivy_*Linux-64bit.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-ARM.deb)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-ARM.deb
      #     path: ./dist/trivy_*Linux-ARM.deb
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-ARM.rpm)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-ARM.rpm
      #     path: ./dist/trivy_*Linux-ARM.rpm
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-ARM.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-ARM.tar.gz
      #     path: ./dist/trivy_*Linux-ARM.tar.gz
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-ARM64.deb)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-ARM64.deb
      #     path: ./dist/trivy_*Linux-ARM64.deb
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-ARM64.rpm)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-ARM64.rpm
      #     path: ./dist/trivy_*Linux-ARM64.rpm
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-ARM64.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-ARM64.tar.gz
      #     path: ./dist/trivy_*Linux-ARM64.tar.gz   
      #     if-no-files-found: error    

      # - name: Upload artifacts (Linux-PPC64LE.deb)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-PPC64LE.deb
      #     path: ./dist/trivy_*Linux-PPC64LE.deb
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-PPC64LE.rpm)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-PPC64LE.rpm
      #     path: ./dist/trivy_*Linux-PPC64LE.rpm
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-PPC64LE.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-PPC64LE.tar.gz
      #     path: ./dist/trivy_*Linux-PPC64LE.tar.gz    
      #     if-no-files-found: error 

      # - name: Upload artifacts (Linux-s390x.deb)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-s390x.deb
      #     path: ./dist/trivy_*Linux-s390x.deb
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-s390x.rpm)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-s390x.rpm
      #     path: ./dist/trivy_*Linux-s390x.rpm
      #     if-no-files-found: error

      # - name: Upload artifacts (Linux-s390x.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_Linux-s390x.tar.gz
      #     path: ./dist/trivy_*Linux-s390x.tar.gz     
      #     if-no-files-found: error       

      # - name: Upload artifacts (macOS-64bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_macOS-64bit.tar.gz
      #     path: ./dist/trivy_*macOS-64bit.tar.gz  
      #     if-no-files-found: error

      # - name: Upload artifacts (macOS-ARM64.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_macOS-ARM64.tar.gz
      #     path: ./dist/trivy_*macOS-ARM64.tar.gz   
      #     if-no-files-found: error   

      # - name: Upload artifacts (OpenBSD-32bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_OpenBSD-32bit.tar.gz
      #     path: ./dist/trivy_*OpenBSD-32bit.tar.gz 
      #     if-no-files-found: error 

      # - name: Upload artifacts (OpenBSD-64bit.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_OpenBSD-64bit.tar.gz
      #     path: ./dist/trivy_*OpenBSD-64bit.tar.gz  
      #     if-no-files-found: error   

      # - name: Upload artifacts (OpenBSD-ARM.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_OpenBSD-ARM.tar.gz
      #     path: ./dist/trivy_*OpenBSD-ARM.tar.gz 
      #     if-no-files-found: error 

      # - name: Upload artifacts (OpenBSD-ARM64.tar.gz)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy_OpenBSD-ARM64.tar.gz
      #     path: ./dist/trivy_*OpenBSD-ARM64.tar.gz
      #     if-no-files-found: error