name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types:
            # test
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            BREAKING

          scopes:
            # checks
            vuln
            misconf
            secret
            # mode
            image
            fs
            repo
            sbom
            server
            # os
            alpine
            redhat
            alma
            rocky
            mariner
            oracle
            debian
            ubuntu
            amazon
            suse
            photon
            distroless
            # language
            ruby
            php
            python
            nodejs
            rust
            dotnet
            java
            go
            # vuln
            os
            lang
            # config
            kubernetes
            dockerfile
            terraform
            cloudformation
            # container
            docker
            podman
            containerd
            oci
            # cli
            cli
            flag
            # others
            helm
            report
            db
            deps