name: Call a reusable workflow

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

  call-workflow-1:
    uses: ./.github/workflows/test.yaml

  call-workflow-2:
    needs: [call-workflow-1]
    uses: ./.github/workflows/test2.yaml