name: test
on:
  workflow_call:
    secrets:
      TEST_SECRET:
        required: false

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: files
        run: echo $TEST_SECRET