name: Test

on: ['push']

jobs:
  test1:
    name: Test push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create image
        run: |
          echo "FROM hello-world" > Dockerfile
          docker build -t dmitriylewen/test2:ci .
          docker images
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: DmitriyLewen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install crane
        uses: imjasonh/setup-crane@v0.1

      - name: Push image
        run: |
          docker save dmitriylewen/test2:ci test.tar
          crane push test.tar dmitriylewen/test2:ci