name: test
on:
  workflow_call:
    secrets:
      TEST_SECRET:
        required: false

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: secret1
        run: echo ${{ secrets.TEST_SECRET}}
      - name: secret2
        run: echo ${{ secrets.TEST_SECRETT}}