name: Test

on: ['push']

jobs:
  test1:
    name: Test push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: create image
        run: |
          echo "FROM hello-world" > Dockerfile
          docker buildx build --platform linux/amd64 --load -t dmitriylewen/trivy:canary-amd64 .
          docker buildx build --platform linux/arm64 --load -t dmitriylewen/trivy:canary-arm64 .
          docker buildx build --platform linux/amd64 --load -t ghcr.io/dmitriylewen/trivy:canary-amd64 .
          docker buildx build --platform linux/arm64 --load -t ghcr.io/dmitriylewen/trivy:canary-arm64 .
          docker images
      - name: Login to docker.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dmitriylewen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install crane
        uses: imjasonh/setup-crane@v0.1

      - name: Push image
        run: |
          docker push dmitriylewen/trivy:canary-amd64
          docker push dmitriylewen/trivy:canary-arm64
          
          docker manifest create \
          dmitriylewen/trivy:canary \
          --amend dmitriylewen/trivy:canary-amd64 \
          --amend dmitriylewen/trivy:canary-arm64
          docker manifest push dmitriylewen/trivy:canary
          
          docker push ghcr.io/dmitriylewen/atcdemo:canary-amd64
          docker push ghcr.io/dmitriylewen/atcdemo:canary-arm64
          
          docker manifest create \
          ghcr.io/dmitriylewen/atcdemo/:canary \
          --amend ghcr.io/dmitriylewen/atcdemo:canary-amd64 \
          --amend ghcr.io/dmitriylewen/atcdemo:canary-arm64
          docker manifest push ghcr.io/dmitriylewen/atcdemo:canary
