name: test
on:
  workflow_call:
    inputs:
      goreleaser_file:
        description: 'file path to GoReleaser file'
        default: 'goreleaser-canary.ymlll'
        required: false
        type: string
      goreleaser_options:
        description: 'GoReleaser options'
        default: '--snapshot'
        required: false
        type: string

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...