name: Test

on: ['push']

jobs:
  test1:
    name: Test push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: create image
        run: |
          echo "FROM hello-world" > Dockerfile
          docker buildx build --platform linux/amd64 --load -t dmitriylewen/test2:amd64 .
          docker buildx build --platform linux/arm64 --load -t dmitriylewen/test2:arm64 .
          docker images
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: DmitriyLewen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install crane
        uses: imjasonh/setup-crane@v0.1

      - name: Push image
        run: |
          docker save dmitriylewen/test2:amd64 > amd64.tar
          docker save dmitriylewen/test2:arm64 > arm64.tar
          crane auth login index.docker.io -u "${{ secrets.DOCKERHUB_USER }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
          crane push . dmitriylewen/test2:ci2