name: Call a reusable workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test.yaml
        with:
          goreleaser_options: '--snapshot'