name: test2
on:
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: TestsWebhook
        run: |
          pwd
          ls -ahl

      - name: TestsGitHubService
        run: go version
