name: Tests

on: ['push']

jobs:
  test1:
    name: Test push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create image
        run: |
          echo "FROM hello-world" > Dockerfile
          docker build -t dmitriylewen/test2:ci .
          docker images
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: DmitriyLewen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test retag and pushing single destination image
        uses: akhilerm/tag-push-action@experiment
        with:
          src: dmitriylewen/test2:ci
          dst: |
            ghcr.io/dmitriylewen/atcDemo:test